name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📅 Isocalendar Fullyear
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      # - name: Commit & Push
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add -A .
      #     git commit -m "generated"
      #     git push
